### ISSUE TITLE
Why does the one_gen_simple.slim only reproduce 2 generations?

### ISSUE THREAD

**Issue by JiaoBingke** [MesserLab/Homing_Mechanisms_with_multiplexed_gRNAs#1]
Hi, Sam.

Thank you for your excellent works on gene drive simulation. I am a new hand in the gene drive and I have some questions about your SLiM script. I wish you can give me some help. 
The _one_gen_simple.slim_ head said that the program starts with two individuals: one of whom is heterozygous female, and generates CAPACITY offspring. However, in the end of program, the population only reproduced two generations, like below. 
```
//// PROGRAM END CONDITION.
2 late() {
    sim.simulationFinished();
}
```
When I increased the number before late() from 2 to 10 and run the slim script in SLiMgui, the program stopped after 2 generations and the SLiMgui did not respond to the mouse click and the program probably crashed. Why did this happen? 

Other SLiM script can often reproduce unlimited generations, such as _panmictic_simple.slim_. Is this problem related to the reproduction() ? The reproduction() in _one_gen_simple.slim_ is copied below.
```
//// REPRODUCTION RULES.
reproduction(NULL, "F") {
    // There are only two individuals; the female's mate is the only male.
    mate = subpop.sampleIndividuals(1, sex="M");

    // The pair generates CAPACITY number of offspring.
    for (i in seqLen(CAPACITY)) {
        // Add offspring to the subpopulation.
        offspring = subpop.addCrossed(individual, mate);
    }
}
```

**Comment by samchamper** [comment]
Hey! Thanks for the excellent question!

The purpose of the "one_gen" models is to empirically measure all of the possible outcomes of a single cross between two individuals configured with a particular gene drive.

In a non-gene-drive context, the outcomes of a cross between two individuals are pretty easy to determine. E.g., if two heterozygotes for a gene A reproduce (Aa crossed with Aa), you'll get the following ratio of offspring:
AA : 25%
Aa : 50%
aa : 25%

However, in the gene drive case this is not nearly as straightforward, especially with a multiplexed drive. So these models serve to experimentally measure the results of a cross.

To accomplish this, the simulation starts with only two individuals, and those individuals produce an enormous number of offspring. If you tried to run the simulation forward another generation, it probably won't work since each of those offspring will try to produce an enormous number of offspring of their own, which will either take a very long time to compute, or possibly just use too much memory and then crash. That is because there is no density-dependent control of the population size in this model (as the point of these models was just to be run for a single generation anyway).

I hope that clears it up!

**Comment by JiaoBingke** [comment]
I get to know that the reproduction() will be called for every individuals. So the third generation population size will be 10000*10000. It's a huge number. Thanks for your detailed explanation.
